version: '3'
services:
  pi:
    image: docker.artifactory/node-version:pi
    ports:
      - "3000:3000"
    networks:
      - overlay
    restart: always
    privileged: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
  overlay:
